### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by harphere** [lone-faerie/taskerha#1]
Hi, this looks great. I'm having an issue with setting up the integration in HA:
```
This error originated from a custom integration.


Logger: custom_components.tasker
Source: custom_components/tasker/__init__.py:319
Integration: Tasker (documentation)
First occurred: 1:59:55 PM (36 occurrences)
Last logged: 2:52:05 PM

Error on first refresh
Traceback (most recent call last):
  File "/config/custom_components/tasker/__init__.py", line 319, in async_config_entry_first_refresh
    await self.async_fetch_all()
  File "/config/custom_components/tasker/__init__.py", line 429, in async_fetch_all
    g.name for g in await self.client.async_get_globals() or []
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/taskerapi/__init__.py", line 431, in async_get_globals
    global_vars = [
                  ^
  File "/usr/local/lib/python3.11/site-packages/taskerapi/__init__.py", line 432, in <listcomp>
    TaskerGlobalDecoded(**g) for g in
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "/usr/local/lib/python3.11/site-packages/taskerapi/typing.py", line 67, in __post_init__
    self.value = base64.b64decode(self.value).decode('ascii')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 148: ordinal not in range(128)
```
I populate the Host field with my phone IP address then submit the integration. I then get a notice on my phone to allow the API key generation, I then enter my phone PIN, the screen in HA says 'Success' but then fails to load the integration with this error.

**Comment by marcomow** [comment]
+1

**Comment by marcomow** [comment]
@harphere I managed to get passed the issue by creating a dummy scene in tasker, @lone-faerie I think you should edit the code to handle the case where tasker doesn't have scenes configured

**Comment by harphere** [comment]
Hey @marcomow, do you mind elaborating on what you mean by 'creating a dummy scene'? Thanks!

**Comment by marcomow** [comment]
In tasker, I've created a new scene. That's it.

**Comment by harphere** [comment]
I tried this again on a different device (Pixel 5) and got it working straight away without creating a dummy scene. Once my primary device comes back from repair, I will try it again. Closing for now.
